routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// /password/forgot -> /forgot-password -> password.request             -> /password/forgot
// /password/email -> /forgot-password -> password.email                -> /
// /password/reset/{token} -> /reset-password/{token} -> password.reset
// /password/reset -> /reset-password -> password.update

use Harmony\Http\Controllers\AdminUserController;
use Harmony\Http\Controllers\DashboardController;
use Harmony\Http\Controllers\RoleController;
use Harmony\Http\Controllers\User\ForgotPasswordController;
use Harmony\Http\Controllers\User\LoginController;
use Harmony\Http\Controllers\User\ResetPasswordController;
use Harmony\Http\Controllers\UserGroupController;
use Illuminate\Support\Facades\Route;

Route::group([
    'middleware' => ['web'],
    'prefix' => config('platform.prefix'),
    'namespace' => 'Harmony\Http\Controllers\User',
    'as' => 'admin.',
], function () {
    // login / logout
    Route::get('/login', [LoginController::class, 'showLoginForm'])->name('login');
    Route::post('login', [LoginController::class, 'login'])->name('login.post');
    Route::post('logout', [LoginController::class, 'logout'])->name('logout');

    // reset password
    Route::get('password/reset', [ForgotPasswordController::class, 'showLinkRequestForm'])->name('password.request');
    Route::post('password/email', [ForgotPasswordController::class, 'sendResetLinkEmail'])->name('password.email');

    Route::get('password/reset/{token}', [ResetPasswordController::class, 'showResetForm'])->name('password.reset');
    Route::post('password/reset', [ResetPasswordController::class, 'reset'])->name('password.update');
});

Route::group([
    'middleware' => ['web', 'admin.auth:admin', 'permission'],
    'prefix' => config('platform.prefix'),
    'as' => 'admin.',
    'namespace' => 'Harmony\Http\Controllers',
], function () {
    // dashboard
    Route::get('', [DashboardController::class, 'index'])->name('dashboard');

    Route::post('admin-user-image-upload', 'AdminUserController@upload')->name('admin-user-image-upload');

    // resources
    Route::resource('admin-user', 'AdminUserController')->except('show');
    Route::resource('role', 'RoleController')->except('show');
    Route::resource('user-group', 'UserGroupController')->except('show');
});

resources/views/admin.blade.php
@extends('platform::layouts.app')

@section('meta_title')
    Harmony Platform eCommerce Admin Dashboard
@endsection

@section('page_title')
    <div class="flex items-center text-gray-800">
        <div class="text-xl font-semibold text-red-700">
            Dashboard
        </div>
    </div>
@endsection

@section('content')
    <div class="flex justify-around my-5">
        {!! $orderWidget->render() !!}
        {!! $customerWidget->render() !!}
        {!! $revenueWidget->render() !!}
    </div>

    <div class="flex justify-around my-5 mt-5">
        <div class="w-full bg-white border border-gray-400 rounded">
            <div class="p-4 font-semibold border-b text-md">
                Admin Dashboard
            </div>
        </div>
    </div>
@endsection

resources/views/breadcrumb/index.blade.php
<div class="mt-1 ml-1 flex items-center">
    @if (isset($breadcrumb->parents) && $breadcrumb->parents->count() > 0)
        @foreach ($breadcrumb->parents as $parentBreadcrumb)
            <div class="ml-1">
                <a href="{{ route($parentBreadcrumb->route) }}">
                    {{ __($parentBreadcrumb->label) }}
                </a>
            </div>
        @endforeach
    @endif

    <div class="ml-1">{{ __($breadcrumb->label) }}</div>
</div>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Harmony Platform eCommerce') }}</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">
        <link rel="shortcut icon" href="{{ asset('vendor/platform/img/favicon.png') }}">

        <!-- Styles -->
        @if (file_exists(public_path('mix-manifest.json')))
            <link href="{{ mix('vendor/platform/css/app.css') }}" rel="stylesheet">
        @else
            <link href="{{ asset('vendor/platform/css/app.css') }}" rel="stylesheet">
        @endif
    </head>
    <body>
        <div id="app">

            <vh-alert></vh-alert>
            <vh-confirm></vh-confirm>
            <vh-layout inline-template>

                <div class="flex items-start">
                    <div :class="sidebar ? 'w-16 z-0 transition sidebar-collapsed duration-500' : 'w-64'">
                        @include('platform::partials.sidebar')
                    </div>

                    <div class="w-full">
                        <div class="w-full">
                            @include('platform::partials.header')
                            @include('platform::partials.flash')
                            @include('platform::partials.breadcrumb')

                            <h1 class="mx-4 my-3">
                                @yield('page_title')
                            </h1>

                            <div class="rounded p-5 mx-3 my-3 bg-white">
                                {{-- <router-view></router-view> --}}
                                @yield('content')
                            </div>

                            @include('platform::partials.footer')
                        </div>
                    </div>
                </div>
            </vh-layout>
        </div>

        <!-- Scripts -->
        @if (file_exists(public_path('mix-manifest.json')))
            <script src="{{ mix('vendor/platform/js/platform.js') }}" defer></script>
        @else
            <script src="{{ asset('vendor/platform/js/platform.js') }}" defer></script>
        @endif

        @stack('scripts')

        @if (file_exists(public_path('mix-manifest.json')))
            <script src="{{ mix('vendor/platform/js/app.js') }}" defer></script>
        @else
            <script src="{{ asset('vendor/platform/js/app.js') }}" defer></script>
        @endif
    </body>
</html>

resources/views/partials/breadcrumb.blade.php
<div class="my-3 ml-4">
    {!! Breadcrumb::render(request()->route()->getName()) !!}
</div>

resources/views/partials/flash.blade.php
<vh-flash notify="{{ session()->get('notification') }}" inline-template>
    <div></div>
</vh-flash>

resources/views/partials/footer.blade.php
<footer class="text-gray-700 body-font">
    <div class="container px-5 py-8 mx-auto flex items-center sm:flex-row flex-col">
        <a class="flex title-font font-medium items-center md:justify-start justify-center text-gray-900">
            <img src="{{ asset('vendor/platform/img/logo-only.svg') }}" class="h-10 w-10" />
        </a>

        <p class="text-sm text-gray-500 sm:pl-4 sm:border-l-2 sm:border-gray-200 sm:py-2 sm:mt-0 mt-4">
            &copy; {{ date('Y') }} — Harmony
        </p>
    </div>
</footer>

resources/views/partials/header.blade.php
<div class="p-0 bg-white shadow z-1">
    <div class="flex items-center h-16 px-3 py-2">
        <div class="ml-3 mr-auto cursor-pointer">
            <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5" @click="sidebar = !sidebar">
                <path d="M1 1h18v2H1V1zm6 8h12v2H7V9zm-6 8h18v2H1v-2zM7 5h12v2H7V5zm0 8h12v2H7v-2zM1 6l4 4-4 4V6z"/>
            </svg>
        </div>

        <div class="flex items-center ml-auto mr-3">
            <div class="relative inset-0" @click="isVisible = false">
                <div class="relative inline-block" @mouseover="isVisible = true" @mouseleave="isVisible = false" @keydown.enter="isVisible = !isVisible">
                    <button type="button" class="inline-flex items-center justify-between px-2 py-1 font-medium text-gray-700 transition-all duration-500 rounded-md focus:outline-none focus:text-brand-900 sm:focus:shadow-outline">
                        <span class="flex-shrink-0">
                            {{ Auth::guard('admin')->user()->full_name }}
                        </span>
                        <svg fill="currentColor" viewBox="0 0 20 20" class="flex-shrink-0 w-5 h-5 ml-1">
                            <path :class="{ 'rotate-180': isVisible }" class="transition duration-300 ease-in-out origin-center transform" fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd"></path>
                        </svg>
                    </button>

                    <transition
                        enter-active-class="transition duration-300 ease-out transform"
                        enter-class="scale-95 -translate-y-3 opacity-0"
                        enter-to-class="scale-100 translate-y-0 opacity-100"
                        leave-active-class="transition duration-150 ease-in transform"
                        leave-class="translate-y-0 opacity-100"
                        leave-to-class="-translate-y-3 opacity-0"
                    >
                        <div v-show="isVisible" class="absolute w-full pt-2">
                            <div class="relative py-3 mt-2 bg-white border border-gray-200">
                                <a href="{{ route('admin.logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();" class="w-full px-4 py-4 font-medium text-gray-700 transition duration-300 ease-in-out hover:bg-gray-100 focus:outline-none hover:text-gray-900 focus:text-gray-900 focus:shadow-outline">
                                    Logout
                                </a>

                                <form id="logout-form" action="{{ route('admin.logout') }}" method="POST" style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </div>
                    </transition>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/partials/sidebar.blade.php
<div class="bg-white border-r min-h-screen">
    <div class="flex items-center">
        <a href="{{ route('admin.dashboard') }}" class="flex items-center mt-2">
            <img class="h-12 block ml-6 w-12" src="{{ asset('vendor/platform/img/logo-only.svg') }}" />
            <div class="text-xl text-red-600" :class="sidebar ? 'hidden' : ''">&nbsp; Harmony</div>
        </a>
    </div>

    <nav class="mt-10">
        @foreach ($adminMenus as $key => $adminMenu)
            <vh-menu :sidebar="sidebar" :menu="{{ json_encode($adminMenu) }}"></vh-menu>
        @endforeach
    </nav>
</div>

resources/views/role/create.blade.php
@extends('platform::layouts.app')

@section('meta_title')
    {{ __('Harmony Platform eCommerce') }}
@endsection

@section('page_title')
    <div class="text-gray-800 flex items-center">
        <div class="text-xl text-red-700 font-semibold">
            {{ __('Role Create') }}
        </div>
    </div>
@endsection

@section('content')
    <div class="flex items-center">
        {{--  --}}
    </div>
@endsection

resources/views/role/edit.blade.php
@extends('platform::layouts.app')

@section('meta_title')
    {{ __('Harmony Platform eCommerce') }}
@endsection

@section('page_title')
    <div class="text-gray-800 flex items-center">
        <div class="text-xl text-red-700 font-semibold">
            {{ __('Role Edit') }}
        </div>
    </div>
@endsection

@section('content')
    <div class="flex items-center">
        {{--  --}}
    </div>
@endsection

resources/views/role/index.blade.php
@extends('platform::layouts.app')

@section('meta_title')
    {{ __('Harmony Platform eCommerce') }}
@endsection

@section('page_title')
    <div class="text-gray-800 flex items-center">
        <div class="text-xl text-red-700 font-semibold">
            {{ __('Role List') }}
        </div>
        <div class="ml-auto">
            <a href="{{ route('admin.role.create') }}" class="px-4 py-2 font-semibold leading-7 text-white hover:text-white bg-red-600 rounded hover:bg-red-700">
                <svg class="w-5 h-5 inline-block text-white" fill="currentColor" viewBox="0 0 24 24">
                    <path d="M17 11a1 1 0 0 1 0 2h-4v4a1 1 0 0 1-2 0v-4H7a1 1 0 0 1 0-2h4V7a1 1 0 0 1 2 0v4h4z"/>
                </svg>
                {{ __('Create') }}
            </a>
        </div>
    </div>
@endsection

@section('content')
    {{--  --}}
@endsection

resources/views/system/configuration/index.blade.php
@extends('platform::layouts.app')

@section('page_title')
    <div class="text-gray-800 flex items-center">
        <div class="text-xl text-red-700 font-semibold">
            Configuration
        </div>
    </div>
@endsection

@section('content')
    <div class="flex items-center">
        <div class="p-5 w-full block border">
            <configuration-save base-url="{{ asset(config('platform.prefix')) }}" inline-template>
                <form method="post" v-on:submit="handleSubmit" action="{{ route('admin.configuration.store') }}">
                    @csrf

                    <vh-tabs>
                        @foreach ($tabs as $tab)
                            <vh-tab identifier="{{ $tab->key() }}" name="{{ $tab->label() }}">
                                @php
                                    $path = $tab->view();
                                @endphp
                                @include($path)
                            </vh-tab>
                        @endforeach
                    </vh-tabs>

                    <div class="mt-3 py-3">
                        <button type="submit" class="px-6 py-3 font-semibold leading-7 text-white hover:text-white bg-red-600 rounded hover:bg-red-700">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-4 inline-flex w-4" fill="currentColor" viewBox="0 0 20 20">
                                <path d="M0 2C0 .9.9 0 2 0h14l4 4v14a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2zm5 0v6h10V2H5zm6 1h3v4h-3V3z"/>
                            </svg>
                            <div class="ml-3">Save</div>
                        </button>

                        <a href="{{ route('admin.configuration.index') }}" class="px-6 py-3 font-semibold inline-block text-white leading-7 hover:text-white bg-gray-500 rounded hover:bg-gray-600">
                            <span class="leading-7">
                                Cancel
                            </span>
                        </a>
                    </div>
                </form>
            </configuration-save>
        </div>
    </div>
@endsection

resources/views/system/role/_fields.blade.php
<div class="mt-3 flex w-full">
    <vh-input
        label-text="{{ __('Name') }}"
        field-name="name"
        init-value="{{ $role->name ?? '' }}"
        error-text="{{ $errors->first('name') }}"
    ></vh-input>
</div>

<div class="mt-3 flex w-full">
    <vh-input
        label-text="{{ __('Description') }}"
        field-name="description"
        init-value="{{ $role->description ?? '' }}"
        error-text="{{ $errors->first('description') }}"
    ></vh-input>
</div>

<div class="flex flex-wrap">
    @foreach ($permissions as $group)
        <div class="mt-3 w-1/4">
            <div class="ml-3 rounded border">
                <div class="p-5 border-b">
                    {{ $group->label() }}
                </div>
                <div class="p-5">
                    @foreach ($group->collections as $permission)
                        <div class="mt-1 flex w-full">
                            <vh-toggle
                                label-text="{{ $permission->label() }}"
                                field-name="permissions[{{ $permission->routes() }}]"
                                init-value="{{ (isset($role) && $role->hasPermission($permission->routes())) ? 1 : 0 }}"
                            ></vh-toggle>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>
    @endforeach
</div>

resources/views/system/role/create.blade.php
@extends('platform::layouts.app')

@section('page_title')
    <div class="text-gray-800 flex items-center">
        <div class="text-xl text-red-700 font-semibold">
            Role Create
        </div>
    </div>
@endsection

@section('content')
    <div class="flex items-center">
        <role-save base-url="{{ asset(config('platform.prefix')) }}" inline-template>
            <div class="w-full block">
                <form method="post" action="{{ route('admin.role.store') }}" @submit="handleSubmit">
                    @csrf

                    <vh-tabs>
                        @foreach ($tabs as $tab)
                            <vh-tab identifier="{{ $tab->key() }}" name="{{ $tab->label() }}">
                                @php
                                    $path = $tab->view();
                                @endphp
                                @include($path)
                            </vh-tab>
                        @endforeach
                    </vh-tabs>

                    <div class="mt-3 py-3">
                        <button type="submit" class="px-6 py-3 font-semibold leading-7 text-white hover:text-white bg-red-600 rounded hover:bg-red-700">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-4 inline-flex w-4" fill="currentColor" viewBox="0 0 20 20">
                                <path d="M0 2C0 .9.9 0 2 0h14l4 4v14a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2zm5 0v6h10V2H5zm6 1h3v4h-3V3z"/>
                            </svg>
                            <span class="ml-3">Save</span>
                        </button>

                        <a href="{{ route('admin.role.index') }}" class="px-6 py-3 font-semibold inline-block text-white leading-7 hover:text-white bg-gray-500 rounded hover:bg-gray-600">
                            <span class="leading-7">
                                Cancel
                            </span>
                        </a>
                    </div>
                </form>
            </div>
        </role-save>
    </div>
@endsection

resources/views/system/role/edit.blade.php
@extends('platform::layouts.app')

@section('meta_title')
    {{ __('Harmony Platform eCommerce') }}
@endsection

@section('page_title')
    <div class="flex items-center text-gray-800">
        <div class="text-xl font-semibold text-red-700">
            {{ __('Role Edit') }}
        </div>
    </div>
@endsection

@section('content')
    <div class="flex items-center">
        <role-save base-url="{{ asset(config('platform.prefix')) }}" role="{{ $role }}" inline-template>
            <div class="block w-full">
                <form method="post" action="{{ route('admin.role.update', $role->id) }}" @submit="handleSubmit">
                    @csrf
                    @method('put')

                    <vh-tabs>
                        @foreach ($tabs as $tab)
                            <vh-tab identifier="{{ $tab->key() }}" name="{{ $tab->label() }}">
                                @php
                                    $path = $tab->view();
                                @endphp
                                @include($path)
                            </vh-tab>
                        @endforeach
                    </vh-tabs>

                    <div class="py-3 mt-3">
                        <button type="submit" class="px-6 py-3 font-semibold leading-7 text-white bg-red-600 rounded hover:text-white hover:bg-red-700">
                            <svg xmlns="http://www.w3.org/2000/svg" class="inline-flex w-4 h-4" fill="currentColor" viewBox="0 0 20 20">
                                <path d="M0 2C0 .9.9 0 2 0h14l4 4v14a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2zm5 0v6h10V2H5zm6 1h3v4h-3V3z"/>
                            </svg>
                            <span class="ml-3">Save</span>
                        </button>

                        <a href="{{ route('admin.role.index') }}" class="inline-block px-6 py-3 font-semibold leading-7 text-white bg-gray-500 rounded hover:text-white hover:bg-gray-600">
                            <span class="leading-7">
                                Cancel
                            </span>
                        </a>
                    </div>
                </form>
            </div>
        </role-save>
    </div>
@endsection

resources/views/system/role/index.blade.php
@extends('platform::layouts.app')

@section('page_title')
    <div class="flex items-center text-gray-800">
        <div class="text-xl font-semibold text-red-700">
            Role List
        </div>
        <div class="ml-auto">
            <a href="{{ route('admin.role.create') }}" class="px-4 py-2 font-semibold leading-7 text-white bg-red-600 rounded hover:text-white hover:bg-red-700">
                <svg class="inline-block w-5 h-5 text-white" fill="currentColor" viewBox="0 0 24 24">
                    <path d="M17 11a1 1 0 0 1 0 2h-4v4a1 1 0 0 1-2 0v-4H7a1 1 0 0 1 0-2h4V7a1 1 0 0 1 2 0v4h4z"/>
                </svg>
                Create
            </a>
        </div>
    </div>
@endsection

@section('content')
    <role-table
        :init="{{ json_encode($roles) }}"
        base-url="{{ asset(config('platform.prefix')) }}"
    ></role-table>
@endsection

resources/views/user/admin-user/_fields.blade.php
<div class="flex w-full mt-3">
    <vh-input>
        label-text="{{ __('First Name') }}"
        field-name="first_name"
        init-value="{{ $adminUser->first_name ?? '' }}"
        error-text="{{ $errors->first('first_name') }}"
    ></vh-input>
</div>

<div class="flex w-full mt-3">
    <vh-input
        label-text="{{ __('Last Name') }}"
        field-name="last_name"
        init-value="{{ $adminUser->last_name ?? '' }}"
        error-text="{{ $errors->first('last_name') }}"
    ></vh-input>
</div>

resources/views/user/admin-user/create.blade.php
@extends('platform::layouts.app')

@section('page_title')
    <div class="flex items-center text-gray-800">
        <div class="text-xl font-semibold text-red-700">
            {{ __('Admin User Create') }}
        </div>
    </div>
@endsection

@section('content')
    <div class="flex items-center">
        <admin-user-save base-url="{{ asset(config('platform.prefix')) }}" inline-template>
            <div class="block w-full">
                <form method="post" action="{{ route('admin.admin-user.store') }}">
                    @csrf
                </form>
            </div>
        </admin-user-save>
    </div>
@endsection

resources/views/user/admin-user/edit.blade.php
@extends('platform::layouts.app')

@section('page_title')
    <div class="text-gray-800 flex items-center">
        <div class="text-xl text-red-700 font-semibold">
            {{ __('Admin User Edit') }}
        </div>
    </div>
@endsection

@section('content')
    <div class="flex items-center">
        <admin-user-save base-url="{{ asset(config('platform.prefix')) }}" :admin-user="{{ $adminUser }}" inline-template>
            <div class="w-full">
                <form method="post" action="{{ route('admin.admin-user.update', $adminUser->id) }}">
                    @csrf
                    @method('put')

                    <vh-tabs>
                        @foreach ($tabs as $tab)
                            <vh-tab identifier="{{ $tab->key() }}" name="{{ $tab->label() }}">
                                @php
                                    $path = $tab->view();
                                @endphp

                                @include($path)
                            </vh-tab>
                        @endforeach
                    </vh-tabs>

                    <div class="mt-3 py-3">
                        <button type="submit" class="px-6 py-3 font-semibold leading-7 text-white hover:text-white bg-red-600 rounded hover:bg-red-700">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-4 inline-flex w-4" fill="currentColor" viewBox="0 0 20 20">
                                <path d="M0 2C0 .9.9 0 2 0h14l4 4v14a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2zm5 0v6h10V2H5zm6 1h3v4h-3V3z"/>
                            </svg>

                            <span class="ml-3">{{ __('Save') }}</span>
                        </button>

                        <a href="{{ route('admin.admin-user.index') }}" class="px-6 py-3 font-semibold inline-block text-white leading-7 hover:text-white bg-gray-500 rounded hover:bg-gray-600">
                            <span class="leading-7">
                                {{ __('Cancel') }}
                            </span>
                        </a>
                    </div>
                </form>
            </div>
        </admin-user-save>
    </div>
@endsection

resources/views/user/admin-user/index.blade.php
@extends('platform::layouts.app')

@section('page_title')
    <div class="text-gray-800 flex items-center">
        <div class="text-xl text-red-700 font-semibold">
            {{ __('Admin User') }}
        </div>

        <div class="ml-auto">
            <a href="{{ route('admin.admin-user.create') }}" class="px-4 py-2 font-semibold leading-7 text-white hover:text-white bg-red-600 rounded hover:bg-red-700">
                <svg class="w-5 h-5 inline-block text-white" fill="currentColor" viewBox="0 0 24 24">
                    <path d="M17 11a1 1 0 0 1 0 2h-4v4a1 1 0 0 1-2 0v-4H7a1 1 0 0 1 0-2h4V7a1 1 0 0 1 2 0v4h4z"/>
                </svg>
                {{ __('Create') }}
            </a>
        </div>
    </div>
@endsection

@section('content')
    <admin-user-table
        :init="{{ json_encode($adminUsers) }}"
        base-url="{{ asset(config('platform.prefix')) }}"
    ></admin-user-table>
@endsection

resources/views/user/user-group/index.blade.php
@extends('platform::layouts.app')

@section('page_title')
    <div class="flex items-center text-gray-800">
        <div class="text-xl font-semibold text-red-700">
            {{ __('User Group List') }}
        </div>

        <div class="ml-auto">
            <a href="{{ route('admin.user-group.create') }}" class="px-4 py-2 font-semibold leading-7 text-white bg-red-600 rounded hover:text-white hover:bg-red-700">
                <svg class="inline-block w-5 h-5 text-white" fill="currentColor" viewBox="0 0 24 24">
                    <path d="M17 11a1 1 0 0 1 0 2h-4v4a1 1 0 0 1-2 0v-4H7a1 1 0 0 1 0-2h4V7a1 1 0 0 1 2 0v4h4z"/>
                </svg>
                {{ __('Create') }}
            </a>
        </div>
    </div>
@endsection

@section('content')
    <div>
        <user-group-table></user-group-table>
    </div>
@endsection

resources/views/widget/total-customer.blade.php
<div class="w-64 cursor-pointer bg-red-600 ml-3 border text-center b-gray-400 rounded items-center p-6 text-white">
    <div class="text-md border-b pb-3 font-bold w-full">
        <span class="uppercase">
            {{ __('Total Customer') }}
        </span>
    </div>

    <div class="flex mt-5 text-center justify-around items-center">
        <div class="w-12 h-12">
            <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                <path d="M7 8a4 4 0 1 1 0-8 4 4 0 0 1 0 8zm0 1c2.15 0 4.2.4 6.1 1.09L12 16h-1.25L10 20H4l-.75-4H2L.9 10.09A17.93 17.93 0 0 1 7 9zm8.31.17c1.32.18 2.59.48 3.8.92L18 16h-1.25L16 20h-3.96l.37-2h1.25l1.65-8.83zM13 0a4 4 0 1 1-1.33 7.76 5.96 5.96 0 0 0 0-7.52C12.1.1 12.53 0 13 0z"/>
            </svg>
        </div>

        <div class="text-4xl ml-5 font-bold">
            {{ $value }}
        </div>
    </div>
</div>

resources/views/widget/total-order.blade.php
<div class="w-64 cursor-pointer bg-purple-500 ml-3 border text-center b-gray-400 rounded items-center p-6 text-white">
    <div class="text-md border-b pb-3 font-bold w-full">
        <span class="uppercase">
            {{ __('Total Order') }}
        </span>
    </div>

    <div class="flex mt-5 text-center justify-around items-center">
        <div class="w-12 h-12">
            <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                <path d="M18 6V4H2v2h16zm0 4H2v6h16v-6zM0 4c0-1.1.9-2 2-2h16a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4zm4 8h4v2H4v-2z"/>
            </svg>
        </div>

        <div class="text-4xl ml-5 font-bold">
            {{ $value }}
        </div>
    </div>
</div>

resources/views/widget/total-revenue.blade.php
<div class="w-64 cursor-pointer bg-blue-600 ml-3 border text-center b-gray-400 rounded items-center p-6 text-white">
    <div class="text-md border-b pb-3 font-bold w-full">
        <span class="uppercase">
            {{ __('Total Revenue') }}
        </span>
    </div>

    <div class="flex mt-5 text-center justify-around items-center">
        <div class="w-12 h-12">
            <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                <path d="M4.13 12H4a2 2 0 1 0 1.8 1.11L7.86 10a2.03 2.03 0 0 0 .65-.07l1.55 1.55a2 2 0 1 0 3.72-.37L15.87 8H16a2 2 0 1 0-1.8-1.11L12.14 10a2.03 2.03 0 0 0-.65.07L9.93 8.52a2 2 0 1 0-3.72.37L4.13 12zM0 4c0-1.1.9-2 2-2h16a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4z"/>
            </svg>
        </div>

        <div class="text-4xl ml-5 font-bold">
            {{ $value }}
        </div>
    </div>
</div>